theme: jekyll-theme-minimal
title: Epistasis Lab
description: This is the documentation page for the Epistasis Lab, a research group in the [Institute for Bioinformatics](http://upibi.org/) at UPenn.
